mysql:
    image: mysql:5.7
    container_name: database.dev
    volumes:
        - ./mysql_init/oms.sql:/oms.sql
        - ./mysql_init:/docker-entrypoint-initdb.d
    ports:
        - "13306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root 
        MYSQL_DATABASE: oms
        MYSQL_USER: oms
        MYSQL_PASSWORD: oms

php:
    build: .
    volumes:
        - ./slim_api:/code/api
        - ./coupon:/code/coupon
    links:
        - mysql 


web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./slim_api:/code/api
        - ./coupon:/code/coupon
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php    

